import productImage1 from '../../public/productImage1.png';
import productImage2 from '../../public/productImage2.png';
import productImage3 from '../../public/productImage3.png';
import productImage4 from '../../public/productImage4.png';
import productImage5 from '../../public/productImage5.png';
import productImage6 from '../../public/productImage6.png';
import productImage7 from '../../public/productImage7.png';
import productImage8 from '../../public/productImage8.png';
import productImage9 from '../../public/productImage9.png';
import productImage10 from '../../public/productImage10.png';
import productImage11 from '../../public/productImage11.png';
import productImage12 from '../../public/productImage12.png';
import productImage13 from '../../public/productImage13.png';
import productImage14 from '../../public/productImage14.png';
import productImage15 from '../../public/productImage15.png';
import productImage16 from '../../public/productImage16.png';
import productImage17 from '../../public/productImage17.png';
import productImage18 from '../../public/productImage18.png';

export const products = [
  {
    id: 1,
    name: 'Vegetable Interior Decor ',
    description: '',
    img: productImage1,
    label: 'Nordic dining chairs',
    price: 130,
    prevPrice: 155,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 2,
    name: 'Mid-century chair design',
    description: '',
    img: productImage2,
    label: 'FINELY Modern Rustic',
    price: 120,
    prevPrice: 150,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 3,
    name: 'Modern living room interior design',
    description: '',
    img: productImage3,
    label: 'Living Room Furniture',
    price: 110,
    prevPrice: 130,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 4,
    name: 'Modern arm chair design ',
    description: '',
    img: productImage4,
    label: 'Nordic dining chairs',
    price: 150,
    prevPrice: 180,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 5,
    name: 'Chic mid-century modern',
    description: '',
    img: productImage5,
    label: 'FINELY Modern Rustic',
    price: 130,
    prevPrice: 160,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 6,
    name: 'Purple sofa with copy space',
    description: '',
    img: productImage6,
    label: 'Living Room Furniture',
    price: 100,
    prevPrice: 120,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 7,
    name: 'Livingroom interior ',
    description: '',
    img: productImage7,
    label: 'Nordic dining chairs',
    price: 180,
    prevPrice: 220,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 8,
    name: 'White living room sofa ',
    description: '',
    img: productImage8,
    label: 'FINELY Modern Rustic',
    price: 700,
    prevPrice: 1000,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 9,
    name: 'Contemporary design with a white chair',
    description: '',
    img: productImage9,
    label: 'Living Room Furniture',
    price: 500,
    prevPrice: 800,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 10,
    name: 'Modern living room sofa ',
    description: '',
    img: productImage10,
    label: 'Nordic dining chairs',
    price: 1000,
    prevPrice: 1500,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 11,
    name: 'A modern living room sofa ',
    description: '',
    img: productImage11,
    label: 'Nordic dining chairs',
    price: 800,
    prevPrice: 1000,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 12,
    name: 'Modern arm chair furniture',
    description: '',
    img: productImage12,
    label: 'FINELY Modern Rustic',
    price: 200,
    prevPrice: 250,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 13,
    name: 'Green Sofa',
    description: '',
    img: productImage13,
    label: 'Living Room Furniture',
    price: 200,
    prevPrice: 150,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 14,
    name: 'Grey sofa ',
    description: '',
    img: productImage14,
    label: 'Nordic dining chairs',
    price: 300,
    prevPrice: 400,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 15,
    name: 'Boho style sofa chair',
    description: '',
    img: productImage15,
    label: 'FINELY Modern Rustic',
    price: 180,
    prevPrice: 200,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 16,
    name: 'Front view arm chair design concept ',
    description: '',
    img: productImage16,
    label: 'Nordic dining chairs',
    price: 550,
    prevPrice: 600,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 17,
    name: 'Room decor with potted plants and sofa',
    description: '',
    img: productImage17,
    label: 'FINELY Modern Rustic',
    price: 1500,
    prevPrice: 1800,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 18,
    name: 'View of futuristic sofa design',
    description: '',
    img: productImage18,
    label: 'Living Room Furniture',
    price: 350,
    prevPrice: 400,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
];
