import productImage1 from '../../public/productImage1.png';
import productImage2 from '../../public/productImage2.png';
import productImage3 from '../../public/productImage3.png';
import productImage4 from '../../public/productImage4.png';
import productImage5 from '../../public/productImage5.png';
import productImage6 from '../../public/productImage6.png';
import productImage7 from '../../public/productImage7.png';
import productImage8 from '../../public/productImage8.png';
import productImage9 from '../../public/productImage9.png';
import productImage10 from '../../public/productImage10.png';
import productImage11 from '../../public/productImage11.png';
import productImage12 from '../../public/productImage12.png';
import productImage13 from '../../public/productImage13.png';
import productImage14 from '../../public/productImage14.png';
import productImage15 from '../../public/productImage15.png';
import productImage16 from '../../public/productImage16.png';
import productImage17 from '../../public/productImage17.png';
import productImage18 from '../../public/productImage18.png';

export const products = [
  {
    id: 1,
    name: 'Nordic dining chairs ',
    description: '',
    img: productImage1,
    label: 'Nordic dining chairs',
    price: 140,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 2,
    name: 'Wood Dining Table',
    description: '',
    img: productImage2,
    label: 'FINELY Modern Rustic',
    price: 100,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 3,
    name: 'Living Room Furniture',
    description: '',
    img: productImage3,
    label: 'Living Room Furniture',
    price: 230,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 4,
    name: 'Nordic dining chairs ',
    description: '',
    img: productImage4,
    label: 'Nordic dining chairs',
    price: 165,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 5,
    name: 'Wood Dining Table',
    description: '',
    img: productImage5,
    label: 'FINELY Modern Rustic',
    price: 310,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 6,
    name: 'Living Room Furniture',
    description: '',
    img: productImage6,
    label: 'Living Room Furniture',
    price: 650,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 7,
    name: 'Nordic dining chairs ',
    description: '',
    img: productImage7,
    label: 'Nordic dining chairs',
    price: 140,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 8,
    name: 'Wood Dining Table',
    description: '',
    img: productImage8,
    label: 'FINELY Modern Rustic',
    price: 100,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 9,
    name: 'Living Room Furniture',
    description: '',
    img: productImage9,
    label: 'Living Room Furniture',
    price: 230,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 10,
    name: 'Nordic dining chairs ',
    description: '',
    img: productImage10,
    label: 'Nordic dining chairs',
    price: 165,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 11,
    name: 'Nordic dining chairs ',
    description: '',
    img: productImage11,
    label: 'Nordic dining chairs',
    price: 140,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 12,
    name: 'Wood Dining Table',
    description: '',
    img: productImage12,
    label: 'FINELY Modern Rustic',
    price: 100,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 13,
    name: 'Living Room Furniture',
    description: '',
    img: productImage13,
    label: 'Living Room Furniture',
    price: 230,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 14,
    name: 'Nordic dining chairs ',
    description: '',
    img: productImage14,
    label: 'Nordic dining chairs',
    price: 165,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 15,
    name: 'Wood Dining Table',
    description: '',
    img: productImage15,
    label: 'FINELY Modern Rustic',
    price: 100,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 16,
    name: 'Nordic dining chairs ',
    description: '',
    img: productImage16,
    label: 'Nordic dining chairs',
    price: 140,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 17,
    name: 'Wood Dining Table',
    description: '',
    img: productImage17,
    label: 'FINELY Modern Rustic',
    price: 100,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
  {
    id: 18,
    name: 'Living Room Furniture',
    description: '',
    img: productImage18,
    label: 'Living Room Furniture',
    price: 230,
    prevPrice: 110,
    category: 'sofa',
    cart_prev_img: '',
    amount: 1,
  },
];
