import productCard from '../../public/product-card.png';

export const products = [
  {
    id: 1,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 2,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 3,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 4,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 5,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 6,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 7,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 8,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 9,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 10,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 11,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 12,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 13,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 14,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 15,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 16,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 17,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 18,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 19,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 20,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 21,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 22,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 23,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 24,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 25,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 26,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 27,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 28,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 29,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 30,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '150',
    trending: false,
  },
  {
    id: 31,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '200',
    prevPrice: '',
    trending: true,
  },
  {
    id: 32,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '100',
    prevPrice: '',
    trending: true,
  },
  {
    id: 33,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '300',
    prevPrice: '',
    trending: true,
  },
  {
    id: 34,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '500',
    prevPrice: '',
    trending: true,
  },
  {
    id: 35,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '400',
    prevPrice: '',
    trending: true,
  },
  {
    id: 36,
    name: 'Wooden Plant Stand',
    img: productCard,
    price: '150',
    prevPrice: '',
    trending: true,
  },
];
